### ISSUE TITLE
Add `PodDisruptionBudget` for `StatefulSet` controlplane

### ISSUE THREAD

**Issue by mattmoor** [chainguard-dev/hakn#6]
Downstream we use something like:
```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controlplane
  namespace: ...
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: controlplane
```
